In [1]:
import pandas as pd

df = pd.DataFrame({
    "부서": ["영업", "영업", "개발", "개발", "인사"],
    "이름": ["철수", "영희", "민수", "지수", "길동"],
    "매출": [100, 150, 200, 250, 120]
})

display(df)

   부서  이름   매출
0  영업  철수  100
1  영업  영희  150
2  개발  민수  200
3  개발  지수  250
4  인사  길동  120

In [2]:
result = df.groupby("부서")["매출"].mean()

display(result)

부서
개발    225.0
영업    125.0
인사    120.0
Name: 매출, dtype: float64

In [3]:
# 부서별 매출 합계
display(df.groupby("부서")["매출"].sum())

# 부서별 매출 평균
display(df.groupby("부서")["매출"].mean())

# 부서별 데이터 개수
display(df.groupby("부서")["매출"].count())

# 부서별 최대 매출
display(df.groupby("부서")["매출"].max())

# 부서별 최소 매출
display(df.groupby("부서")["매출"].min())

부서
개발    450
영업    250
인사    120
Name: 매출, dtype: int64

부서
개발    225.0
영업    125.0
인사    120.0
Name: 매출, dtype: float64

부서
개발    2
영업    2
인사    1
Name: 매출, dtype: int64

부서
개발    250
영업    150
인사    120
Name: 매출, dtype: int64

부서
개발    200
영업    100
인사    120
Name: 매출, dtype: int64

In [4]:
df.groupby('부서')['매출'].describe()

    count   mean        std    min    25%    50%    75%    max
부서
개발    2.0  225.0  35.355339  200.0  212.5  225.0  237.5  250.0
영업    2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0
인사    1.0  120.0        NaN  120.0  120.0  120.0  120.0  120.0

In [5]:
import pandas as pd

df = pd.DataFrame({
    "부서": ["영업", "영업", "개발", "개발", "인사"],
    "이름": ["철수", "영희", "민수", "지수", "길동"],
    "매출": [100, 150, 200, 250, 120]
})

display(df)

   부서  이름   매출
0  영업  철수  100
1  영업  영희  150
2  개발  민수  200
3  개발  지수  250
4  인사  길동  120

In [6]:
df.groupby("부서")["매출"].transform("mean")

0    125.0
1    125.0
2    225.0
3    225.0
4    120.0
Name: 매출, dtype: float64

In [7]:
df["부서평균매출"] = df.groupby("부서")["매출"].transform("mean")

In [8]:
df["성별평균나이"] = df.groupby("성별")["나이"].transform("mean")

KeyError: '성별'