In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

df2 = pd.DataFrame({
    "이름": ["최유진", "정현우", "강수빈"],
    "점수": [95, 80, 88]
})

In [ ]:
# 1. concat()을 사용하여 df1과 df2를 행 방향으로 결합하시오.
result = pd.concat([df1, df2], ignore_index=True) #ignore_index = True: 인덱스 정렬

print(result)

    이름  점수
0  김민준  85
1  이서연  90
2  박지훈  75
3  최유진  95
4  정현우  80
5  강수빈  88

In [3]:
# 2. 두 DataFrame을 열 방향으로 결합하시오.
result_axis1 = pd.concat([df1, df2], axis=1)
print(result_axis1)

    이름  점수   이름  점수
0  김민준  85  최유진  95
1  이서연  90  정현우  80
2  박지훈  75  강수빈  88

In [4]:
# 3. 학생ID를 기준으로 두 DataFrame을 결합하시오.

students = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"]
})

scores = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "점수": [85, 90, 75, 95]
})

result = pd.merge(students, scores, on="학생ID")

print(result)

   학생ID   이름  점수
0   101  김민준  85
1   102  이서연  90
2   103  박지훈  75
3   104  최유진  95

In [5]:
# 4. 고객ID를 기준으로 두 DataFrame을 merge()하시오.
# 결과에 다음 컬럼이 포함되도록 하시오.
# 고객ID, 이름, 상품, 금액

customer = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "이름": ["김민준", "이서연", "박지훈"]
})

order = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "상품": ["노트북", "마우스", "키보드"],
    "금액": [1200000, 30000, 80000]
})

result = pd.merge(customer, order, on="고객ID")
print(result)

   고객ID   이름   상품       금액
0     1  김민준  노트북  1200000
1     2  이서연  마우스    30000
2     3  박지훈  키보드    80000

In [6]:
# 5. 부서ID를 기준으로 두 DataFrame을 결합하여 다음과 같은 결과를 만드시오.

employee = pd.DataFrame({
    "사번": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"],
    "부서ID": [10, 20, 10, 30]
})

department = pd.DataFrame({
    "부서ID": [10, 20, 30],
    "부서명": ["개발팀", "인사팀", "영업팀"]
})

result = pd.merge(employee, department, on="부서ID")
print(result)

    사번   이름  부서ID  부서명
0  101  김민준    10  개발팀
1  102  이서연    20  인사팀
2  103  박지훈    10  개발팀
3  104  최유진    30  영업팀

In [10]:
# 6. 
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, None, 80],
    "출석": [True, True, None, True, None]
})

df

    이름    점수    출석
0  김민준  85.0  True
1  이서연   NaN  True
2  박지훈  90.0  None
3  최유진   NaN  True
4  정현우  80.0  None

In [11]:
# 6-① 결측치의 위치를 확인하시오.
print("① 결측치 위치:")
print(df.isna()) # 또는 df.isnull() 사용 가능

① 결측치 위치:
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4  False  False   True

In [12]:
# 6-② 각 컬럼의 결측치 개수를 확인하시오.
print("② 컬럼별 결측치 개수:")
print(df.isna().sum())

② 컬럼별 결측치 개수:
이름    0
점수    2
출석    2
dtype: int64

In [13]:
# 6-③ 전체 결측치의 개수를 구하시오.
print("③ 전체 결측치 개수:")
print(df.isna().sum().sum())

③ 전체 결측치 개수:
4

In [14]:
# 7. 점수에 결측치가 있는 행을 삭제하시오.

df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진"],
    "점수": [85, None, 90, 75]
})

result = df.dropna(subset=["점수"])
print(result)

    이름    점수
0  김민준  85.0
2  박지훈  90.0
3  최유진  75.0

In [15]:
# 8.
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [80, None, 90, 70, None]
})

df

    이름    점수
0  김민준  80.0
1  이서연   NaN
2  박지훈  90.0
3  최유진  70.0
4  정현우   NaN

In [16]:
# 8-① 점수의 평균을 구하시오. - pandas는 결측치 자동 제외 후 평균 계산
mean_score = df["점수"].mean()
print(f"① 점수 평균: {mean_score}")

① 점수 평균: 80.0

In [21]:
# 8-② 결측치를 평균으로 대체하시오.
# 8-③ 처리된 DataFrame을 출력하시오.
df["점수"] = df["점수"].fillna(mean_score)
df

    이름    점수
0  김민준  80.0
1  이서연  80.0
2  박지훈  90.0
3  최유진  70.0
4  정현우  80.0

In [23]:
# 9.
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "지역": ["서울", "부산", None, "서울", None]
})

df

    이름   지역
0  김민준   서울
1  이서연   부산
2  박지훈  NaN
3  최유진   서울
4  정현우  NaN

In [ ]:
# 9-① 지역의 최빈값을 구하시오.
# mode()는 시리즈(Series) 형태로 반환되므로 가장 첫 번째 값([0])을 추출

mode_region = df["지역"].mode()[0]
print(f"① 지역 최빈값: {mode_region}")

① 지역 최빈값: 서울

In [ ]:
# 9-② 결측치를 최빈값으로 대체하시오.
# 9-③ 처리된 DataFrame을 출력하시오.

df["지역"] = df["지역"].fillna(mode_region)
df

    이름  지역
0  김민준  서울
1  이서연  부산
2  박지훈  서울
3  최유진  서울
4  정현우  서울

In [26]:
# 10. 학생 정보와 시험 점수가 각각 다른 DataFrame에 저장되어 있다.

students = pd.DataFrame({
    "학생ID": [101, 102, 103, 104, 105],
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"]
})

scores = pd.DataFrame({
    "학생ID": [101, 102, 104, 105],
    "점수": [85, None, 90, 75]
})

display(students)
display(scores)

   학생ID   이름
0   101  김민준
1   102  이서연
2   103  박지훈
3   104  최유진
4   105  정현우

   학생ID    점수
0   101  85.0
1   102   NaN
2   104  90.0
3   105  75.0

In [28]:
# ① 학생ID를 기준으로 두 DataFrame을 merge()하시오.
# ② 모든 학생이 결과에 포함되도록 하시오.

merged_df = pd.merge(students, scores, on="학생ID", how="left")
merged_df

   학생ID   이름    점수
0   101  김민준  85.0
1   102  이서연   NaN
2   103  박지훈   NaN
3   104  최유진  90.0
4   105  정현우  75.0

In [29]:
# ③ 점수의 결측치 개수를 확인하시오.

missing_count = merged_df["점수"].isna().sum()
print(f"③ 점수 결측치 개수: {missing_count}개")

③ 점수 결측치 개수: 2개

In [34]:
# ④ 점수의 평균값으로 결측치를 대체하시오.
# ⑤ 최종 DataFrame을 출력하시오.

mean_score = merged_df["점수"].mean()
merged_df["점수"] = merged_df["점수"].fillna(mean_score)
merged_df

   학생ID   이름         점수
0   101  김민준  85.000000
1   102  이서연  83.333333
2   103  박지훈  83.333333
3   104  최유진  90.000000
4   105  정현우  75.000000