In [1]:
import pandas as pd

In [4]:
# {레이블: [], 레이블: [] ...}
df1 = pd.DataFrame({
                    "이름":["민수","지영"],
                    "점수":[90,85]
                    })

# print() #터미널출력
# display() #노트북 셀에 최적화 출력

print(df1)
display(df1)

   이름  점수
0  민수  90
1  지영  85

   이름  점수
0  민수  90
1  지영  85

In [7]:
#index값 행 레이블(레이블 인덱스), columns 값 열 레이블(레이블 인덱스)
df2 = pd.DataFrame([
    ["민수", 90], #1행
    ["지영", 85], #2행
], index = ["첫번째","두번째"], columns = ["이름", "점수"]
)

df2

     이름  점수
첫번째  민수  90
두번째  지영  85

In [9]:
df3 = pd.DataFrame([
    {"이름":"민수", "점수":90},
    {"이름":"지영", "점수":100}
])

df3

   이름   점수
0  민수   90
1  지영  100

In [11]:
# numpy의 2차원 배열 - 모든 데이터 타입이 동일
import numpy as np

df3 = pd.DataFrame(np.array([
    [1, 2], 
    [3, 4]
]), columns = ["x", "y"])

df3

   x  y
0  1  2
1  3  4

In [12]:
# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

print(df)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [13]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
df.columns

Index(['이름', '나이', '성별'], dtype='str')

In [15]:
df.values

array([['철수', 20, '남'],
       ['영희', 21, '여'],
       ['민수', 20, '남'],
       ['지영', 22, '여'],
       ['준호', 21, '남']], dtype=object)

In [17]:
df.dtypes #반환값 series 타입

이름      str
나이    int64
성별      str
dtype: object

In [18]:
print(df.shape, df.size, df.ndim)

(5, 3) 15 2

In [ ]:
# 저장 단위
# KB -> MB-> GB -> TB -> PB -> EB -> ZB -> YB

In [20]:
df.head()

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [22]:
# [] 인덱싱 연산자 매개값 index 사용(행 레이블, 열 레이블, 표현식)
df["성별"].unique()

<StringArray>
['남', '여']
Length: 2, dtype: str

In [ ]:
# loc[행옵션, 열옵션]: 레이블 인덱스
# iloc[행옵션, 열옵션]: 위치값

In [23]:
df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

print(df)

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [24]:
df.loc['B'] #df.loc['B', :]

이름    이영희
학년      2
점수     92
Name: B, dtype: object

In [25]:
df.loc['B', '점수']

np.int64(92)

In [26]:
import seaborn as sns

In [28]:
mpg_df = sns.load_dataset("mpg")
mpg_df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [30]:
# [5, 10, 15, 20] > 10 # [false, false, true, true]
[x>10 for x in [5, 10, 15, 20]]

[False, False, True, True]

In [31]:
[x for x in [5, 10, 15, 20] if x>10]

[15, 20]

In [32]:
type(df["점수"])

pandas.Series

In [ ]:
# 리스트 > 10 -> 문법적 에러 -> 컴프리핸션
# narray
# 시리즈 > 10 -> 문법적 에러