In [1]:
import pandas as pd

In [ ]:
# SQL 예
# 집합연산(UNION, ..., 행, 열) -> concat
# JOIN (key값(컬럼값) 합친다) -> merge

# df.concat(df2)

In [2]:
import pandas as pd

df1 = pd.DataFrame({
    "이름": ["홍길동", "김철수"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["이영희", "박민수"],
    "점수": [85, 95]
})

display(df1)
display(df2)

    이름  점수
0  홍길동  80
1  김철수  90

    이름  점수
0  이영희  85
1  박민수  95

In [5]:
df3 = pd.concat([df1, df2], axis=0, ignore_index=True)
df3

    이름  점수
0  홍길동  80
1  김철수  90
2  이영희  85
3  박민수  95

In [6]:
df4 = pd.concat([df1, df2], axis=1, ignore_index=False)
df4

    이름  점수   이름  점수
0  홍길동  80  이영희  85
1  김철수  90  박민수  95

In [3]:
# axis=0 위아래 결합(기본값) -> 행추가
df = pd.concat([df1, df2], ignore_index=False, axis=0) # ignore_index 기본값 False
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
0  이영희  85
1  박민수  95

In [4]:
df = pd.concat([df1, df2], ignore_index=True, axis=0)
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
2  이영희  85
3  박민수  95

In [8]:
df1 = pd.DataFrame({
    "이름": ["김민수", "이서연"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["박지훈", "최유진"],
    "등급": ["A", "B"]
})
display(df1)
display(df2)

    이름  점수
0  김민수  80
1  이서연  90

    이름 등급
0  박지훈  A
1  최유진  B

In [9]:
pd.concat([df1, df2])

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
0  박지훈   NaN    A
1  최유진   NaN    B

In [10]:
pd.concat([df1, df2], join = "inner")

    이름
0  김민수
1  이서연
0  박지훈
1  최유진

In [12]:
# merge 함수: SQL JOIN 유사
import pandas as pd

df_customer = pd.DataFrame({
    "고객ID": [101, 102, 103, 104],
    "이름": ["홍길동", "김철수", "이영희", "박민수"]
})

df_score = pd.DataFrame({
    "고객ID": [101, 102, 103, 105],
    "점수": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

   고객ID   이름
0   101  홍길동
1   102  김철수
2   103  이영희
3   104  박민수

   고객ID  점수
0   101  90
1   102  80
2   103  95
3   105  70

In [13]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95

In [14]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="outer" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN
4   105  NaN  70.0

In [15]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="left" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN

In [16]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="right" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95
3   105  NaN  70